functionsDirectory = "/Users/freyayu/Documents/创业项目/New Loom/网站开发/netlify/functions"
functionsDirectoryOrigin = "default"
plugins = []
headers = []
redirects = []

[build]
publish = "/Users/freyayu/Documents/创业项目/New Loom/网站开发"
publishOrigin = "default"
functions = "/Users/freyayu/Documents/创业项目/New Loom/网站开发/netlify/functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[functions]

[functions."*"]